// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM1P41klu1pTVILP9_zE9rHzcDZEx5Xw8',
    appId: '1:594290911366:web:23108b5045f3d5d4318907',
    messagingSenderId: '594290911366',
    projectId: 'xiiner',
    authDomain: 'xiiner.firebaseapp.com',
    storageBucket: 'xiiner.appspot.com',
    measurementId: 'G-RX8XCYMCEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVVrb98AztR3SH_KXiM0cdb86Yd4LjAZc',
    appId: '1:594290911366:android:f27e13be8f1a213c318907',
    messagingSenderId: '594290911366',
    projectId: 'xiiner',
    storageBucket: 'xiiner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3YrP28k12FJpMQQBhFH95Ta0GsKKiI-o',
    appId: '1:594290911366:ios:f31f3f20f55b1859318907',
    messagingSenderId: '594290911366',
    projectId: 'xiiner',
    storageBucket: 'xiiner.appspot.com',
    iosBundleId: 'com.example.xinner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3YrP28k12FJpMQQBhFH95Ta0GsKKiI-o',
    appId: '1:594290911366:ios:94db674bff4450ea318907',
    messagingSenderId: '594290911366',
    projectId: 'xiiner',
    storageBucket: 'xiiner.appspot.com',
    iosBundleId: 'com.example.xinner.RunnerTests',
  );
}
